
bankwithlist: bankwithlist.o singlylinked.o #doublylinked.o
	g++ bankwithlist.cpp singlylinked.cpp -o bankwithlist#doublylinked.cpp -o bankwithlist

clean:
	rm -f *.o
real_clean: clean
	rm -f vectors bankwithlist singlylinked doublylinked
